---
title: "MA615 Text Mining Task II Report"
author: "Yifeng He"
date: "2021/12/05"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning=F,message = F,echo=F,highlight=F)
pacman::p_load(
tidyverse,
magrittr,
knitr,
gutenbergr,
tidytext,
sentimentr
)
```

## Task I Book Choice

The book I chose is 'The Origin of The Family, Private Property and the State' by Friedrich Engles.

```{r}

# gutenberg_metadata
# gutenberg_works(str_detect(author, "Zweig"))

my_book=gutenberg_download(c(33111))
write.table(my_book,'Book2.txt',row.names = F)

```

```{r}
library(tnum)
tnum.authorize("mssp1.bu.edu")
tnum.setSpace("test2")
source("Book2TN-v6A-1.R")
```

```{r}
mybook<-read.table('Book2.txt')
```

## TASK II



```{r}
#my_book=mybook
tidy_books <- my_book %>%
  mutate(
    linenumber = row_number(),
    chapter = cumsum(str_detect(text, 
                                regex("^chapter [\\divxlc]", 
                                      ignore_case = TRUE)))) %>%
  unnest_tokens(word, text)
```


```{r}
afinn <- tidy_books %>% 
  inner_join(get_sentiments("afinn")) %>% 
  group_by(index = linenumber %/% 80) %>% 
  summarise(sentiment = sum(value)) %>% 
  mutate(method = "AFINN")

```



```{r}
afinn <- tidy_books %>% 
  inner_join(get_sentiments("afinn")) %>% 
  group_by(index = linenumber %/% 80) %>% 
  summarise(sentiment = sum(value)) %>% 
  mutate(method = "AFINN")

bing_and_nrc <- bind_rows(
  tidy_books %>% 
    inner_join(get_sentiments("bing")) %>%
    mutate(method = "Bing et al."),
  tidy_books %>% 
    inner_join(get_sentiments("nrc") %>% 
                 filter(sentiment %in% c("positive", 
                                         "negative"))
    ) %>%
    mutate(method = "NRC")) %>%
  count(method, index = linenumber %/% 80, sentiment) %>%
  pivot_wider(names_from = sentiment,
              values_from = n,
              values_fill = 0) %>% 
  mutate(sentiment = positive - negative)
```

```{r fig.cap="sentiment plot"}
#form the book
bind_rows(afinn, 
          bing_and_nrc) %>%
  ggplot(aes(index, sentiment, fill = method)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~method, ncol = 1, scales = "free_y")+
  theme_bw()
```

```{r}
#from the book
bing_word_counts <- tidy_books %>%
  inner_join(get_sentiments("bing")) %>%
  count(word, sentiment, sort = TRUE) %>%
  ungroup()
```

```{r fig.cap="negative positive words count"}
bing_word_counts %>%
  group_by(sentiment) %>%
  slice_max(n, n = 10) %>% 
  ungroup() %>%
  mutate(word = reorder(word, n)) %>%
  ggplot(aes(n, word, fill = sentiment)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~sentiment, scales = "free_y") +
  labs(x = "Contribution to sentiment",
       y = NULL)+
  theme_bw()
```



```{r fig.cap='word cloud'}
library(wordcloud)

tidy_books %>%
  anti_join(stop_words) %>%
  count(word) %>%
  with(wordcloud(word, n, max.words = 100))
```



```{r fig.cap="sentiment word cloud"}
#
library(reshape2)
tidy_books %>%
  inner_join(get_sentiments("bing")) %>%
  count(word, sentiment, sort = TRUE) %>%
  acast(word ~ sentiment, value.var = "n", fill = 0) %>%
  comparison.cloud(colors = c("red", "blue"),
                   max.words = 100)
```


## TASK III

### tnum

First I put the book into the tnum database.
	
```{r}
#upload the book
# tnBooksFromLines(mybook$V2, "hvdsb/book4")
```

```{r}
sb12<- tnum.query('hvdsb/book4/section# has text',max=8000) %>% tnum.objectsToDf()
engles_sent<-sb12 %>% separate(col=subject,
                  into = c("path1", "path2","section","paragraph","sentence"),
                  sep = "/",
                  fill = "right") %>%
  select(section:string.value)

#change the string values of 0001 to 1, to simple numeric values
engles_sent<-engles_sent %>% mutate_at(c('section','paragraph','sentence'),~str_extract_all(.,"\\d+") %>% unlist() %>% as.numeric())

#get from the sentimentr github
engles_result<-engles_sent %>% dplyr::mutate(sentence_split = get_sentences(string.value))%$%
    sentiment_by(sentence_split, list(section))

#the sentiment analysis graph of the the book rank from high to low
plot(engles_result)

#the emotional curve for the book
plot(uncombine(engles_result))
```

### Comparison with TASK II


```{r}
#Change from task two "divided by 80" to by chapters.
new_bing<-tidy_books %>% 
    inner_join(get_sentiments("bing")) %>%
    mutate(method = "Bing et al.") %>%
    count(method, index = chapter, sentiment) %>%
  pivot_wider(names_from = sentiment, values_from = n, values_fill = 0) %>% mutate(sentiment = positive - negative)


#standardize the scale of sentiment for task 2 and task 3 for comparison
bing2_rep<-new_bing %>% mutate(engles_scale=scale(sentiment)) %>% select(method,index,engles_scale)
colnames(bing2_rep)[2]='section'

engles_result<-engles_result %>% mutate(sentimentr_scale=scale(ave_sentiment))

#join together two tasks into one data frame
engles_res_2<-left_join(engles_result,bing2_rep,by='section')%>% select(section,engles_scale,sentimentr_scale)
engles_res_plot<-engles_res_2 %>% pivot_longer(cols=c('sentimentr_scale','engles_scale'),names_to = 'sentiment')

#the graph for comparison
engles_res_plot %>%ggplot(aes(y=value,x=factor(section))) +
  geom_bar(aes(fill=factor(sentiment)),stat='identity',position = "dodge",width = 0.7)+theme_bw()

```

